[skyvern]
configs = [
    {"env" = "local", "host" = "http://skyvern:8000/api/v1", "orgs" = [{name="Skyvern", cred="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ5MjA5ODI5NTcsInN1YiI6Im9fNTE2ODU1MzIzNjAzNzM2Mjg2In0.C_I3nVwgwNF1LixUpVfmxALsiOW4EYnH-iZDXgq4fEw"}]}
]
